module.exports = (io, {Order, Rider, RestaurantOwner, MenuItem, Offer, Banner, upload, uploadRider, cloudinary, sendWhatsApp, calculateBill}) => {
const express = require('express');
const router = express.Router();

// ===== MENU API =====
router.post('/menu', upload.single('image'), async (req,res)=>{ try{ let imageUrl = ''; if(req.file){ const result = await cloudinary.uploader.upload(`data:${req.file.mimetype};base64,${req.file.buffer.toString('base64')}`); imageUrl = result.secure_url; } await new MenuItem({...req.body, image: imageUrl}).save(); res.json({success:true, msg:"Item Added"}); }catch(e){ res.json({success:false, msg:e.message}) }});
router.put('/menu/:id', upload.single('image'), async (req,res)=>{ try{ let updateData = {...req.body}; if(req.file){ const result = await cloudinary.uploader.upload(`data:${req.file.mimetype};base64,${req.file.buffer.toString('base64')}`); updateData.image = result.secure_url; } await MenuItem.findByIdAndUpdate(req.params.id, updateData); res.json({success:true, msg:"Item Updated"}); }catch(e){ res.json({success:false, msg:e.message}) }});
router.put('/menu/:id/stock', async (req,res)=>{ try{ const item = await MenuItem.findById(req.params.id); item.inStock =!item.inStock; await item.save(); res.json({success:true}); } catch(e){ res.json({success:false, msg:e.message}) }});
router.delete('/menu/:id', async (req,res)=>{ try{ await MenuItem.findByIdAndDelete(req.params.id); res.json({success:true, msg:"Item Deleted"}); } catch(e){ res.json({success:false, msg:e.message}) }});
router.get('/menu', async (req,res)=> { const shopId = req.query.shop || 'default-shop'; res.json(await MenuItem.find({restaurantId: shopId})); });

// ===== ADMIN APIs =====
router.get('/admin/pending-restaurants', async (req,res)=>{ try{ res.json(await RestaurantOwner.find({status: "Pending"})) } catch(e){ res.status(500).json([]) }});
router.get('/admin/pending-riders', async (req,res)=>{ try{ res.json(await Rider.find({status: "Pending"})) } catch(e){ res.status(500).json([]) }});
router.put('/admin/approve-restaurant/:id', async (req,res)=>{ try{ const trialEnd = new Date(); trialEnd.setDate(trialEnd.getDate() + 30); await RestaurantOwner.findByIdAndUpdate(req.params.id, {status:"Approved", trial_end_date: trialEnd}); res.json({success:true, msg:"Restaurant Approved"}) } catch(e){ res.status(500).json({success:false}) }});
router.put('/admin/reject-restaurant/:id', async (req,res)=>{ try{ await RestaurantOwner.findByIdAndUpdate(req.params.id, {status:"Rejected"}); res.json({success:true, msg:"Restaurant Rejected"}) } catch(e){ res.status(500).json({success:false, msg: e.message}) }});
router.get('/admin/all-restaurants', async (req,res)=>{ try{ const restaurants = await RestaurantOwner.find({}).sort({createdAt: -1}); res.json(restaurants) } catch(e){ res.status(500).json([]) }});
router.put('/admin/approve-rider/:id', async (req,res)=>{ try{ await Rider.findByIdAndUpdate(req.params.id, {status:"Approved"}); res.json({success:true, msg:"Rider Approved"}) } catch(e){ res.status(500).json({success:false}) }});
router.get('/admin/restaurants', async (req,res)=>{ try{ const restaurants = await RestaurantOwner.find({status: "Approved"}); const formatted = restaurants.map(r => ({ _id: r.restaurantId, name: r.restaurantName, address: r.address, mobile: r.mobile, email: r.email, status: r.status, plan_status: r.plan_status, image: r.image, payment_proof: r.payment_proof })); res.json(formatted) } catch(e){ res.status(500).json([]) }});
router.get('/restaurants', async (req,res)=>{ try{ const restaurants = await RestaurantOwner.find({status: "Approved"}); const formatted = restaurants.map(r => ({ _id: r.restaurantId, name: r.restaurantName, address: r.address, image: r.image || `https://via.placeholder.com/400x180/ff6600/ffffff?text=${encodeURIComponent(r.restaurantName)}`, mobile: r.mobile, email: r.email })); res.json(formatted) } catch(e){ res.status(500).json([]) }});
router.get('/admin/approved-riders', async (req,res)=>{ try{ const riders = await Rider.find({status: "Approved"}).select('name mobile'); res.json(riders) } catch(e){ res.json([]) } });
router.post('/admin/assign-rider', async (req,res)=>{ try{ const {orderId, riderId} = req.body; const order = await Order.findOne({trackId: orderId}); if(!order) return res.json({success:false, msg:"Order nahi mila"}); const rider = await Rider.findOne({mobile: riderId}); if(!rider) return res.json({success:false, msg:"Rider nahi mila"}); await Order.findOneAndUpdate({trackId: orderId}, { riderId: riderId, riderName: rider.name, status: 'Out for Delivery' }); io.emit('newOrderForRider', {riderId}); res.json({success:true, msg:"Rider Assigned!"}); }catch(e){ res.json({success:false, msg:e.message}) }});
router.get('/admin/graph', async (req,res)=>{ try{ let data = []; for(let i=6; i>=0; i--){ let d = new Date(); d.setDate(d.getDate()-i); let start = new Date(d); start.setHours(0,0,0,0); let end = new Date(d); end.setHours(23,59,59,999); const orders = await Order.find({createdAt: {$gte: start, $lte: end}}); const revenue = orders.reduce((a,b)=>a+Number(b.grand_total || b.total || 0),0); data.push({date: d.toLocaleDateString('en-IN', {day:'2-digit', month:'short'}), revenue: revenue, orders: orders.length}); } res.json(data) }catch(e){ res.json([]) }});
router.get('/admin/rider-cash', async (req,res)=>{ try{ const riders = await Rider.find({status: "Approved"}); res.json(riders.map(r=>({name:r.name, mobile:r.mobile, pending_cash:r.cash_balance}))) }catch(e){ res.json([]) }});
router.post('/admin/rider-deposit', async (req,res)=>{ try{ await Rider.updateOne({mobile: req.body.mobile}, {$set: {cash_balance: 0}}); res.json({success:true}) }catch(e){ res.json({success:false}) }});
router.get('/admin/promo', async (req,res)=>{ try{ res.json(await Banner.findOne().sort({updatedAt:-1}) || {}) }catch(e){ res.json({}) }});
router.post('/admin/promo', upload.single('bannerImage'), async (req,res)=>{ try{ const existing = await Banner.findOne({}); let imageUrl = existing?.image || ''; if(req.file){ const result = await cloudinary.uploader.upload(`data:${req.file.mimetype};base64,${req.file.buffer.toString('base64')}`, {folder: 'eat4bite-banners'}); imageUrl = result.secure_url; } await Banner.findOneAndUpdate({}, {text: req.body.text, image: imageUrl, color: req.body.color, updatedAt: new Date()}, {upsert: true}); res.json({success:true}) }catch(e){ res.json({success:false, msg:e.message}) }});
router.delete('/admin/promo', async (req,res)=>{ try{ await Banner.deleteMany({}); res.json({success:true}) }catch(e){ res.json({success:false}) }});
router.post('/broadcast', async (req,res)=>{ try{ const owners = await RestaurantOwner.find({status:"Approved"}); owners.forEach(o=> sendWhatsApp(o.mobile, `📢 ADMIN NOTICE: ${req.body.message}`)); res.json({success:true, count: owners.length}) }catch(e){ res.json({success:false}) }});
router.get('/report', async (req,res)=>{ try{ const {start, end, shop} = req.query; let query = {createdAt: {$gte: new Date(start), $lte: new Date(end)}}; if(shop!== 'all') query.restaurantId = shop; const orders = await Order.find(query); res.json({totalOrders: orders.length, totalRevenue: orders.reduce((a,b)=>a+Number(b.grand_total || b.total || 0),0)}) }catch(e){ res.json({totalOrders:0, totalRevenue:0}) }});

// ===== DAILY PAYOUT API =====
router.get('/admin/daily-payout', async (req, res) => {try {const today = new Date().toISOString().split('T')[0];const startOfDay = new Date(today + 'T00:00:00.000Z');const endOfDay = new Date(today + 'T23:59:59.999Z');const orders = await Order.find({ createdAt: { $gte: startOfDay, $lte: endOfDay }, payout_status: "Pending" });let totalSales = 0; let platformFee = 0; let toPay = 0; let result = [];orders.forEach(o => {const sale = Number(o.grand_total || o.total || 0);const fee = sale * 0.10; const pay = sale - fee;totalSales += sale; platformFee += fee; toPay += pay;result.push({ orderId: o.trackId, restaurant: o.restaurantId, amount: sale, fee: fee, toPay: pay });});res.json({date: today, totalOrders: orders.length, totalSales, platformFee, toPay, orders: result});} catch (e) { res.status(500).json({ message: e.message }); }});
router.post('/admin/mark-paid', async (req, res) => {try {const { orderIds } = req.body;await Order.updateMany({ trackId: { $in: orderIds } }, { $set: { payout_status: 'Paid' } });res.json({ success: true, message: 'Marked as Paid' });} catch (e) { res.status(500).json({ message: e.message }); }});

// ===== RIDER APIs =====
router.post('/rider-register', uploadRider.fields([{name: 'aadharImg'}, {name: 'panImg'}, {name: 'photoImg'}]), async (req,res)=>{ try{ const {restaurantId, name, fatherName, aadhar, pan, mobile} = req.body; if(await Rider.findOne({mobile})) return res.json({success:false, msg:"Mobile pehle se registered hai"}); const upload = async (file) => { if(!file) return ""; const result = await cloudinary.uploader.upload(`data:${file[0].mimetype};base64,${file[0].buffer.toString('base64')}`, {folder: 'eat4bite_riders'}); return result.secure_url; } const aadharUrl = await upload(req.files['aadharImg']); const panUrl = await upload(req.files['panImg']); const photoUrl = await upload(req.files['photoImg']); await new Rider({restaurantId, name, fatherName, aadhar, pan, mobile, aadharImg: aadharUrl, panImg: panUrl, photoImg: photoUrl}).save(); res.json({success:true, msg:"Registered! Admin approval ka wait kare"}) }catch(e){ res.json({success:false, msg:e.message}) }});
router.post('/rider-login', async (req,res)=>{ try{ const rider = await Rider.findOne({mobile: req.body.mobile}); if(!rider) return res.json({success:false, msg:"Rider nahi mila"}); if(rider.status === "Pending") return res.json({success:false, msg:"Approval pending hai"}); res.json({success:true, rider}) }catch(e){ res.json({success:false, msg:"Server Error"}) }});
router.put('/rider-status/:id', async (req,res)=>{ try{ await Rider.findByIdAndUpdate(req.params.id, {status: req.body.status}); res.json({success:true}) }catch(e){ res.json({success:false}) }});
router.post('/riderLocation', async (req,res)=>{ try{ await Rider.findOneAndUpdate({mobile: req.body.mobile}, {lat: req.body.lat, lng: req.body.lng, lastUpdate: new Date()}); res.json({success:true}) }catch(e){ res.json({success:false}) }});
router.get('/rider-orders/:mobile', async (req,res)=>{ try{ res.json(await Order.find({riderId: req.params.mobile, status: {$ne: "Delivered"}}).sort({createdAt:-1})) }catch(e){ res.json([]) }});
router.get('/rider/ledger', async (req,res)=>{ try{ const rider = await Rider.findOne({mobile: req.query.riderId}); const today = new Date(); today.setHours(0,0,0,0); const todayOrders = await Order.find({riderId: req.query.riderId, createdAt: {$gte: today}, status: "Delivered"}); const today_collected = todayOrders.reduce((a,b)=>a+Number(b.cashCollected || 0),0); const progress = Math.round((rider.cash_balance / rider.cashLimit) * 100); res.json({pending_cash: rider.cash_balance, today_orders: todayOrders.length, today_collected: today_collected, progress: progress > 100? 100 : progress}) }catch(e){ res.json({}) }});
router.post('/order-delivered', async (req,res)=>{ try{ const {orderId, cashCollected} = req.body; const order = await Order.findById(orderId); await Order.findByIdAndUpdate(orderId, {status: "Delivered", cashCollected: cashCollected}); await Rider.updateOne({mobile: order.riderId}, {$inc: {cash_balance: cashCollected}}); io.emit('orderStatusUpdate', {orderId: orderId, status: "Delivered"}); res.json({success:true}) }catch(e){ res.json({success:false}) }});

// ===== RESTAURANT + ORDER APIs =====
router.post('/restaurant-register', upload.fields([{ name: 'restaurantImage', maxCount: 1 }, { name: 'paymentProof', maxCount: 1 }]), async (req,res)=>{ try{ const {restaurantName, ownerName, mobile, email, address, password, amount} = req.body; let plan = req.body.plan; if(Array.isArray(plan)) plan = plan[0]; const existing = await RestaurantOwner.findOne({$or: [{mobile}, {email}]}); if(existing) return res.json({success:false, msg:"Mobile ya Email pehle se hai"}); let restaurantImageUrl = ""; let paymentProofUrl = ""; if(req.files['restaurantImage']){ const result = await cloudinary.uploader.upload(`data:${req.files['restaurantImage'][0].mimetype};base64,${req.files['restaurantImage'][0].buffer.toString('base64')}`, {folder: 'eat4bite_restaurants'}); restaurantImageUrl = result.secure_url; } if(req.files['paymentProof']){ const result = await cloudinary.uploader.upload(`data:${req.files['paymentProof'][0].mimetype};base64,${req.files['paymentProof'][0].buffer.toString('base64')}`, {folder: 'eat4bite_proofs'}); paymentProofUrl = result.secure_url; } const restaurantId = "shop_" + Date.now(); const regAmount = Number(amount) || 200; const planType = regAmount === 2000? "Annual" : "Trial"; const trialDays = regAmount === 2000? 365 : 7; const trialEnd = new Date(); trialEnd.setDate(trialEnd.getDate() + trialDays); await new RestaurantOwner({ restaurantId, restaurantName, ownerName, mobile, email, address, password, status: "Pending", image: restaurantImageUrl, payment_proof: paymentProofUrl, trial_end_date: trialEnd, plan_status: planType, registration_fee_paid: regAmount, upi_id: "tanbalkhi2014-3@okhdfcbank" }).save(); res.json({ success:true, msg:"Registration ho gayi. Approval ke baad login karna", upi_id: "tanbalkhi2014-3@okhdfcbank" }) }catch(e){ console.log(e); res.json({success:false, msg:e.message}) }});
router.post('/restaurant-login', async (req,res)=>{ try{ const {mobile, password} = req.body; const restaurant = await RestaurantOwner.findOne({mobile}); if(!restaurant) return res.status(400).json({success:false, msg:"Restaurant nahi mila"}); if(restaurant.password!== password) return res.status(400).json({success:false, msg:"Password galat"}); if(restaurant.status!== "Approved") return res.status(400).json({success:false, msg:"Approval pending hai"}); res.json({success:true, shop: restaurant}) }catch(e){ res.status(500).json({success:false, msg:"Server Error"}) }});
router.get('/restaurant/ledger', async (req,res)=>{ try{ const shop = req.query.shop; const today = new Date(); today.setHours(0,0,0,0); const orders = await Order.find({restaurantId: shop, createdAt: {$gte: today}}); const revenue = orders.reduce((a,b)=>a+Number(b.item_total),0); const cod = orders.filter(o=>o.paymentMode=='COD').reduce((a,b)=>a+Number(b.item_total),0); const online = revenue - cod; const payout_due = Math.round(cod * 0.95); res.json({ orders: orders.length, revenue, cod, online, earning: Math.round(cod * 0.95), payout_due }) }catch(e){ res.status(500).json({})}});
router.post('/restaurant/payout', async (req,res)=>{ try{ const {restaurantId} = req.body; await RestaurantOwner.updateOne({restaurantId}, {$set: {payout_due: 0}}); res.json({success:true, msg:"Payout Marked"}) }catch(e){ res.json({success:false}) }});
router.put('/orders/:id/status', async (req,res)=>{ try{ await Order.findByIdAndUpdate(req.params.id, {status: req.body.status}); res.json({success:true}) }catch(e){ res.json({success:false}) }});
router.get('/riders', async (req,res)=>{ try{ res.json(await Rider.find({}).select('name mobile restaurantId cash_balance')) }catch(e){ res.json([]) }});
router.post('/restaurant/cash-confirm', async (req,res)=>{ try{ const {riderId, depositedAmount} = req.body; await Rider.updateOne({mobile: riderId}, {$inc: {cash_balance: -depositedAmount}}); res.json({success:true, msg:"Cash Settled"}) }catch(e){ res.json({success:false}) }});
router.post('/restaurant/offer', async (req,res)=>{ try{ await new Offer({...req.body}).save(); res.json({success:true, msg:"Offer Created"}) }catch(e){ res.json({success:false}) }});
router.post('/orders', async (req,res)=>{const trackId = 'EB' + Date.now();const item_total = req.body.items.reduce((a,b)=>a+(b.price*b.qty), 0);const bill = calculateBill(item_total);const shop = await RestaurantOwner.findOne({restaurantId: req.body.restaurantId});const upi_id = shop? shop.upi_id : "tanbalkhi2014-3@okhdfcbank";const upi_link = `upi://pay?pa=${upi_id}&pn=${shop.restaurantName}&am=${bill.grand_total}&cu=INR&tn=Order${trackId}`;const newOrder = await new Order({...req.body, trackId,...bill, total: bill.grand_total, custLat: req.body.custLat || null, custLng: req.body.custLng || null,paymentMode: req.body.payment || req.body.paymentMode}).save();if(shop && shop.mobile) sendWhatsApp(shop.mobile, `🔔 New Order ${trackId}\nTotal: ₹${bill.grand_total}`);io.emit('newOrder', newOrder);res.json({success:true, trackId, bill, upi_link, upi_id})});
router.get('/orders', async (req,res)=>{ try{ const shop = req.query.shop; if(shop) return res.json(await Order.find({restaurantId: shop}).sort({createdAt:-1})); res.json(await Order.find().sort({createdAt:-1})) } catch(e){ res.status(500).json([]) }});
router.get('/orders/track/:id', async (req,res)=>{ try{ const order = await Order.findOne({trackId: req.params.id}); if(!order) return res.json(null); res.json(order) } catch(e){ res.status(500).json(null) } });

return router;
}